plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.seleniumhq.selenium:selenium-java:4.21.0'
    testImplementation 'org.testng:testng:7.10.2'
    testImplementation 'io.github.bonigarcia:webdrivermanager:5.8.0'
    testImplementation 'com.aventstack:extentreports:5.1.2'
}

test {
    useTestNG() {
        suites 'src/test/resources/testng.xml'
    }

    testLogging {
        events "PASSED", "FAILED", "SKIPPED"
        showStandardStreams = true
        exceptionFormat = "full"
    }

    outputs.upToDateWhen { false }
}